### ISSUE TITLE
Question 

### ISSUE THREAD

**Issue by critesjosh** [Montoya/2048frame#1]
This is sick, thanks for making it. I am exploring dynamic backend content in frames.

Did you use php for technical reasons (how the backend server works) or just because you are familiar with it?

I'm not as familiar with php, so I'd have to learn it. I'm just trying to evaluate possible approaches to solve my problem.

**Comment by Montoya** [comment]
I used PHP because I’m super familiar with it and I already had a server set up for it. I haven’t done much server side JS actually :)
